# Generated by Django 3.0.5 on 2020-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0007_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Applied'), ('2', 'Accepted'), ('3', 'Rejected'), ('4', 'Submitted'), ('5', 'setback'), ('6', 'Completed')], max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Created'), ('2', 'Published'), ('3', 'Closed')], max_length=30),
        ),
    ]
